---
- name: postgres | Include ome.postgresql_client role
  include_role:
    name: ome.postgresql_client

# tasks file for ome.postgresql
- name: postgres | fail if postgresql_users_databases defined
  fail:
    msg: >
      Variable 'postgresql_users_databases' has been replaced by
      'postgresql_databases' and 'postgresql_users'
  when: "postgresql_users_databases | default(False)"

- name: postgres | fail if postgresql_install_server true
  fail:
    msg: >
      Variable 'postgresql_install_server=false' has been replaced by the
      'ome.postgresql_client' role
  when: "not (postgresql_install_server | default(True))"

- import_tasks: redhat.yml
  when: ansible_os_family | lower == 'redhat'

- import_tasks: debian.yml
  when: ansible_os_family | lower == 'debian'

- import_tasks: initialise.yml

- import_tasks: databases.yml
