---
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: postgresql-10-c7
    image: centos/systemd
    image_version: latest
    command: /sbin/init
    privileged: true
  - name: postgresql-11-c7
    image: centos/systemd
    image_version: latest
    command: /sbin/init
    privileged: true
    groups:
      - extra_options
  - name: postgresql-12-c7
    image: centos/systemd
    image_version: latest
    command: /sbin/init
    privileged: true
    groups:
      - extra_options
  - name: postgresql-13-c7
    image: centos/systemd
    image_version: latest
    command: /sbin/init
    privileged: true
    groups:
      - extra_options
  - name: postgresql-14-c7
    image: centos/systemd
    image_version: latest
    command: /sbin/init
    privileged: true
    groups:
      - extra_options
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      postgresql-10-c7:
        postgresql_version: "10"
      postgresql-11-c7:
        postgresql_version: "11"
      postgresql-12-c7:
        postgresql_version: "12"
      postgresql-13-c7:
        postgresql_version: "13"
      postgresql-14-c7:
        postgresql_version: "14"
    group_vars:
      extra_options:
        postgresql_server_conf:
          shared_preload_libraries: "'pg_stat_statements'"
          log_filename: "'postgresql-%F.log'"
  playbooks:
    converge: ../resources/playbook.yml
scenario:
  name: centos7
verifier:
  name: testinfra
  directory: ../resources/tests/
  lint:
    name: flake8
